# Copyright 2021 The Loimos Project Developers.
# See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: MIT

include ../Makefile.include

.PHONY:all
all: $(OBJS)

.PHONY:clean
clean:
	rm -f *.o *.pb.C *.pb.h *.pb.o
