# Set the environment variable CHARM_HOME to the Charm++ installation
CHARM_HOME  ?= /usr/local/charm
CHARMC      = $(CHARM_HOME)/bin/charmc

# Set the environment variable PROTOBUF_HOME to the protobuf installation to
# overide this default
PROTOBUF_HOME ?= /usr/local/protobuf
PROTOC        = $(PROTOBUF_HOME)/bin/protoc

CXX       = g++
OPTS      = -g -O2
CXXFLAGS  = $(OPTS) -std=c++11 -Wall -I$(PROTOBUF_HOME)/include

