name: SMP

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CHARM_HOME: $GITHUB_WORKSPACE/charm
      PROTOBUF_HOME: $GITHUB_WORKSPACE/protobuf

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build Charm++
    - name: build-charm++
      run: |
        git clone https://github.com/UIUC-PPL/charm.git
        cd charm
        git checkout v6.10.2
        ./build charm++ netlrts-linux-x86_64 smp -g -j4 --with-production --enable-error-checking
    # Build protobuf
    - name: build-protobuf
      run: |
        git clone https://github.com/protocolbuffers/protobuf.git
        cd protobuf
        git checkout v3.15.0
        ./autogen.sh
        mkdir build install
        cd build
        ../configure --prefix=$GITHUB_WORKSPACE/protobuf/install
        make -j4 && make install
    # Build and test Loimos
    - name: build-loimos
      run: |
        export PATH=$CHARM_HOME/bin:$PROTOBUF_HOME/bin:$PATH
        export LD_LIBRARY_PATH=$PROTOBUF_HOME/lib:$LD_LIBRARY_PATH
        cd src
        make
        ./charmrun +p4 ./loimos 39 16 1 4 7 ../data/disease_models/h5n1.textproto +ppn 2 +setcpuaffinity ++local
